[build]
command = "npm run build" # Replace with your build command
publish = ". " # Replace with the directory containing your Express.js app
 memory = "4096MB" # You can adjust this value as needed
